# -*- coding: utf-8 -*-
"""rotasi.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IE0JahwmH8MI219BO6OAU1i9CjIVUboL
"""

import imageio as img
import numpy as np
import matplotlib.pyplot as plt

def rotateImage(image, degree):
    radian_deg = np.radians(degree)
    cos_deg, sin_deg = np.cos(radian_deg), np.sin(radian_deg)

    height, width = image.shape[:2]
    # Perkirakan ukuran gambar output (rotasi dari pojok kiri atas)
    max_dim_x = int(abs(width * cos_deg) + abs(height * sin_deg))
    max_dim_y = int(abs(width * sin_deg) + abs(height * cos_deg))

    # Buat gambar output dengan latar belakang putih
    outputImage = np.ones((max_dim_y, max_dim_x, 3), dtype=image.dtype) * 255

    for y in range(height):
        for x in range(width):
            # Hitung koordinat baru setelah rotasi
            newX = int(x * cos_deg - y * sin_deg)
            newY = int(x * sin_deg + y * cos_deg)

            # Cek jika koordinat baru berada dalam batas citra output
            if 0 <= newX < max_dim_x and 0 <= newY < max_dim_y:
                outputImage[newY, newX] = image[y, x]

    return outputImage

# Membaca gambar
image = img.imread("/content/bunga.jpg")  # Gunakan \\ untuk path Windows

# Rotasi gambar sebesar 35 derajat dari pojok kiri atas
rotated_image = rotateImage(image, 35)

# Menampilkan gambar asli dan hasil rotasi
plt.figure(figsize=(10, 5))

plt.subplot(1, 2, 1)
plt.title("Original Image")
plt.imshow(image)

plt.subplot(1, 2, 2)
plt.title("Rotated Image (Pivot at 0,0)")
plt.imshow(rotated_image)

plt.show()