# -*- coding: utf-8 -*-
"""rotasi.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IE0JahwmH8MI219BO6OAU1i9CjIVUboL
"""

import imageio as img
import numpy as np
import matplotlib.pyplot as plt

def rotateImage(image, degree):
    radian_deg = np.radians(degree)
    cos_deg, sin_deg = np.cos(radian_deg), np.sin(radian_deg)

    height, width = image.shape[:2]
    max_dim = int(np.sqrt(height**2 + width**2))  # Ukuran citra output (persegi)
    outputImage = np.zeros((max_dim, max_dim, 3), dtype=image.dtype) + 255  # Latar belakang putih

    centerY, centerX = max_dim // 2, max_dim // 2  # Pusat rotasi

    for y in range(height):
        for x in range(width):
            # Koordinat relatif terhadap pusat gambar asli
            rel_y = y - height // 2
            rel_x = x - width // 2

            # Hitung koordinat baru setelah rotasi
            newX = int(cos_deg * rel_x - sin_deg * rel_y) + centerX
            newY = int(sin_deg * rel_x + cos_deg * rel_y) + centerY

            # Cek jika koordinat baru berada dalam batas citra output
            if 0 <= newX < max_dim and 0 <= newY < max_dim:
                outputImage[newY, newX] = image[y, x]

    return outputImage

# Membaca gambar
image = img.imread("/content/bunga.jpg")  # Gunakan \\ untuk path Windows

# Rotasi gambar sebesar 35 derajat
rotated_image = rotateImage(image, 35)

# Menampilkan gambar asli dan hasil rotasi
plt.subplot(1, 2, 1)
plt.title("Original Image")
plt.imshow(image)

plt.subplot(1, 2, 2)
plt.title("Rotated Image")
plt.imshow(rotated_image)

plt.show()